### ISSUE TITLE
Name collision with R.swift

### ISSUE THREAD

**Issue by mac-cain13** [azurechen/Rauto#1]
Hey @azurechen,

Great to see you working on a open source project and creating a handy tool for fellow developers!

One little thing though, I have a open source project named [R.swift](https://github.com/mac-cain13/R.swift) doing the exact same thing! :open_mouth: I understand you didn't do this on purpose, but it might be a good idea to rename your project to prevent confusion.

What do you think is the best way to resolve this? :)

**Comment by azurechen** [comment]
Hi @mac-cain13,

Sorry for not replying you sooner.

In fact, I didn't know [R.swift](https://github.com/mac-cain13/R.swift) when I started this project, I just want to resolve the problem, but your project continually inspire me. 👍 

I think we both agree **R.swift** is the best name for this function, it is easily associated to **R.java**.
Frankly, I prefer to focus on **plugin**, I believe it will be a helpful tool to implement **R.swift** this concept. It is different and I really want my project keep the name related to R.swift

I am happy to meet somebody care about this issue too, we may try to cooperate. I would like to focus on making the **plugin** better and maybe I can replace the core functions by your library.

Do you think this is a ideal solution? Email me If you are interested 😃

**Comment by mac-cain13** [comment]
Sorry to respond so slow! Busy times over here. :)

I think it would be less confusing if your plugin used [R.swift](https://github.com/mac-cain13/R.swift) to do its job. Then it really is a Xcode plugin version of R.swift so that would be better than it being a different thing.

I would suggest the following to continue if you are going to rewrite it to use R.swift:
1. Add a statement to the readme of this project that it shouldn't be confused with R.swift because this is a completely different thing.
2. Rewrite the project to use R.swift and update the readme to say that this is a plugin version of R.swift.

If you don't intent to or don't have the time to rewrite the project to R.swift I would really like you to change the name to avoid any confusion.
