### ISSUE TITLE
Do not see the options to generate the R.swift after install

### ISSUE THREAD

**Issue by minhanhhere** [azurechen/Rauto#2]
As the readme said:

```
After restarting Xcode, open any project and
The first use
Click Edit -> R.swift -> Enable Auto Sync
If you want to manually sync
Click Edit -> R.swift -> Sync
If you don't use R.swift in this project anymore
Click Edit -> R.swift -> Clean
```

But I do not see any R.swift in menu Edit. Can you give more specific instruction. I'm using XCODE 7.3.1 and install it via Alcatraz Package Manager

**Comment by MostafaTaghipour** [comment]
i have seam problem

**Comment by azurechen** [comment]
Hi @minhanhhere and @MostafaTaghipour,
Thanks for your reports! I have update the plugin to support the newest version of Xcode.
Please **Remove** it by Alcatraz and **install** again
Thank you very much!

**Comment by minhanhhere** [comment]
Wow! Perfect.
Thanks for the quick fix!
